CREATE TABLE IF NOT EXISTS pages (
  id INT CHECK (id > 0) NOT NULL GENERATED ALWAYS AS IDENTITY,
  title VARCHAR(255) NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT NULL /* ON UPDATE CURRENT_TIMESTAMP */,
  PRIMARY KEY (id)
);