
ALTER TABLE user_groups
ADD COLUMN IF NOT EXISTS id INTEGER PRIMARY KEY AUTOINCREMENT
ADD COLUMN IF NOT EXISTS name TEXT NOT NULL
ADD COLUMN IF NOT EXISTS members TEXT NOT NULL
ADD COLUMN IF NOT EXISTS permissions TEXT NOT NULL;