CREATE TABLE IF NOT EXISTS `user_tokens` (
   `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
   `userid` INT UNSIGNED NOT NULL,
   `token` VARCHAR(255) NOT NULL,
   `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   `expires_at` TIMESTAMP
) ENGINE=MyRocks DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
