ALTER TABLE IF EXISTS `user_groups`
ADD COLUMN IF NOT EXISTS `id` int(11) NOT NULL AUTO_INCREMENT,
ADD COLUMN IF NOT EXISTS `name` text NOT NULL,
ADD COLUMN IF NOT EXISTS `members` text NOT NULL,
ADD COLUMN IF NOT EXISTS `permissions` text NOT NULL,
ADD PRIMARY KEY IF NOT EXISTS (`id`);