
ALTER TABLE pages 
ADD COLUMN IF NOT EXISTS id INTEGER PRIMARY KEY AUTOINCREMENT
ADD COLUMN IF NOT EXISTS title TEXT NOT NULL
ADD COLUMN IF NOT EXISTS content TEXT NOT NULL
ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;