
ALTER TABLE IF EXISTS `site_settings`
ADD COLUMN IF NOT EXISTS `key` VARCHAR(191) NOT NULL,
ADD COLUMN IF NOT EXISTS `value` TEXT NOT NULL,
ADD COLUMN IF NOT EXISTS `type` VARCHAR(16) NOT NULL,
ADD PRIMARY KEY IF NOT EXISTS (`key`);