-- Pages
ALTER TABLE IF EXISTS `pages`
ADD COLUMN IF NOT EXISTS `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
ADD COLUMN IF NOT EXISTS `title` VARCHAR(255) NOT NULL,
ADD COLUMN IF NOT EXISTS `content` TEXT NOT NULL,
ADD COLUMN IF NOT EXISTS `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN IF NOT EXISTS `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
ADD PRIMARY KEY IF NOT EXISTS (`id`);