CREATE TABLE IF NOT EXISTS `gandi_api_keychain` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `admin_userid` INT NOT NULL,
    `api_key_b64` VARCHAR(255) NOT NULL,
    `is_active` BOOLEAN NOT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);