
ALTER TABLE `gandi_api_keychain`
    ADD COLUMN IF NOT EXISTS `id` INT AUTO_INCREMENT,
    ADD COLUMN IF NOT EXISTS `admin_userid` INT NOT NULL,
    ADD COLUMN IF NOT EXISTS `api_key_b64` VARCHAR(255) NOT NULL,
    ADD COLUMN IF NOT EXISTS `is_active` BOOLEAN NOT NULL,
    ADD COLUMN IF NOT EXISTS `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,
    ADD PRIMARY KEY IF NOT EXISTS (`id`);
