-- Users

ALTER TABLE `users`
  ADD COLUMN IF NOT EXISTS `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  ADD COLUMN IF NOT EXISTS `username` VARCHAR(255) NOT NULL,
  ADD COLUMN IF NOT EXISTS `password_hash` VARCHAR(255) NOT NULL,
  ADD COLUMN IF NOT EXISTS `email` VARCHAR(255) NOT NULL DEFAULT 'phpizza-noemail@example.org',
  ADD COLUMN IF NOT EXISTS `signed_up_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS `date_of_birth` DATE NOT NULL DEFAULT '2026-03-02',
  ADD COLUMN IF NOT EXISTS `is_child` BOOLEAN,
  ADD COLUMN IF NOT EXISTS `gender` VARCHAR(255) NOT NULL DEFAULT 'unspecified',
  ADD COLUMN IF NOT EXISTS `is_blocked` BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS `is_email_verified` BOOLEAN NOT NULL DEFAULT FALSE,
  ADD PRIMARY KEY IF NOT EXISTS (`id`),
  ADD UNIQUE KEY IF NOT EXISTS `uniq_users_username` (`username`),
  ADD UNIQUE KEY IF NOT EXISTS `uniq_users_email` (`email`);
